# Generated by Django 6.1.1 on 2026-09-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
