# Generated by Django 6.1.1 on 2026-09-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_organizer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_type',
            field=models.CharField(blank=True, choices=[('NGO', 'Registered NGO / Non-Profit'), ('COMMUNITY_KITCHEN', 'Community Kitchen / Langar Seva'), ('RELIGIOUS_TRUST', 'Religious Trust / Temple / Gurudwara / Mosque / Church'), ('INDIVIDUAL', 'Community Contributor')], max_length=50),
        ),
    ]
