# Generated by Django 6.1.1 on 2026-09-23 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVE', 'Approved Submission'), ('REJECT', 'Rejected Submission'), ('STATUS_CHANGE', 'Status Changed'), ('REPORT_RESOLVE', 'Report Resolved'), ('REPORT_DISMISS', 'Report Dismissed')], max_length=32)),
                ('reason_or_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='food.freefoodevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
