# Generated by Django 6.1.1 on 2026-09-23 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFoodEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. Temple Mahaprasad, Community Langar', max_length=255)),
                ('description', models.TextField(help_text='Provide context, event purpose, organizer details, etc.')),
                ('event_type', models.CharField(choices=[('Mahaprasad', 'Mahaprasad'), ('Langar', 'Langar'), ('Wedding', 'Wedding'), ('Religious Event', 'Religious Event'), ('NGO Distribution', 'NGO Food Distribution'), ('Community Event', 'Community Program'), ('Birthday', 'Birthday Celebration'), ('Public Distribution', 'Public Food Distribution'), ('Other', 'Other Free Food Event')], db_index=True, max_length=64)),
                ('food_details', models.TextField(help_text='Describe food items, veg/non-veg, packaging, special instructions')),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Public'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text='Feedback or rejection reason from admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Free Food Event',
                'verbose_name_plural': 'Free Food Events',
                'ordering': ['event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='food.freefoodevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('WRONG_LOCATION', 'Wrong location or map pin'), ('NOT_EXIST', 'Event does not exist'), ('EVENT_OVER', 'Event is already over'), ('INCORRECT_INFO', 'Incorrect food or timing information'), ('MISLEADING', 'Misleading or inappropriate listing'), ('OTHER', 'Other issue')], max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved (Listing Modified/Removed)'), ('DISMISSED', 'Dismissed (False Report)')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='food.freefoodevent')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='freefoodevent',
            index=models.Index(fields=['status', 'event_date'], name='food_freefo_status_077718_idx'),
        ),
        migrations.AddIndex(
            model_name='freefoodevent',
            index=models.Index(fields=['latitude', 'longitude'], name='food_freefo_latitud_7f3afd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'event')},
        ),
    ]
