# Generated by Django 6.1.1 on 2026-09-26 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freefoodevent',
            name='allergens_info',
            field=models.CharField(blank=True, default='', help_text='Allergen notices, e.g. Nut-Free, Gluten-Free, Dairy-Free', max_length=255),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='dietary_type',
            field=models.CharField(choices=[('PURE_VEG', 'Pure Vegetarian'), ('VEGAN', 'Vegan (Plant-Based)'), ('JAIN', 'Jain Food (No Root Veg / Garlic)'), ('HALAL', 'Halal Prepared'), ('VEG_NONVEG', 'Vegetarian & Non-Vegetarian'), ('OTHER', 'Other / Mixed')], db_index=True, default='PURE_VEG', help_text='Dietary suitability filter', max_length=50),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='is_surplus_food',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag for excess celebration food available for volunteer food rescue pickup'),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='is_verified_organizer',
            field=models.BooleanField(db_index=True, default=False, help_text='Verified mark for recognized NGOs, community kitchens, or religious trusts'),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='organizer_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='rescue_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Direct phone number for pickup coordinator', max_length=30),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='rescue_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available for Rescue Pickup'), ('IN_PROGRESS', 'Pickup Claimed / In Progress'), ('COMPLETED', 'Rescued & Distributed')], db_index=True, default='AVAILABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='freefoodevent',
            name='surplus_quantity',
            field=models.CharField(blank=True, default='', help_text='Estimated surplus quantity, e.g. 50+ meals, 3 large vessels', max_length=150),
        ),
        migrations.CreateModel(
            name='FoodRescueClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volunteer_name', models.CharField(max_length=150)),
                ('volunteer_phone', models.CharField(max_length=30)),
                ('organization', models.CharField(blank=True, default='', help_text='NGO or Volunteer Network Name', max_length=255)),
                ('estimated_pickup_time', models.CharField(help_text='e.g. In 30 mins, 4:00 PM', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Vehicle details, container capacity, etc.')),
                ('status', models.CharField(choices=[('CLAIMED', 'Claimed - Volunteer En Route'), ('PICKED_UP', 'Successfully Picked Up / Distributed'), ('CANCELLED', 'Claim Cancelled')], default='CLAIMED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_claims', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_claims', to='food.freefoodevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityLiveStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SERVING', 'Food is currently serving'), ('FINISHED', 'Food finished / over')], max_length=20)),
                ('note', models.CharField(blank=True, default='', help_text='Optional quick note, e.g. line moving fast, sweets finished', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_statuses', to='food.freefoodevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_status_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='food_commun_event_i_5f6f05_idx'), models.Index(fields=['event', 'status'], name='food_commun_event_i_041c91_idx')],
            },
        ),
    ]
