# Generated by Django 6.1.1 on 2026-10-08 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_freefoodevent_allergens_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('FOOD_FINISHED', 'Food Finished'), ('WRONG_LOCATION', 'Wrong Location'), ('WRONG_TIME', 'Wrong Time'), ('DUPLICATE', 'Duplicate'), ('INCORRECT_INFO', 'Incorrect Information'), ('OTHER', 'Other'), ('EVENT_OVER', 'Food Finished / Event Over'), ('NOT_EXIST', 'Event does not exist'), ('MISLEADING', 'Misleading or inappropriate listing')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='freefoodevent',
            index=models.Index(fields=['status', 'event_date', 'start_time'], name='idx_food_status_date_time'),
        ),
        migrations.AddIndex(
            model_name='freefoodevent',
            index=models.Index(fields=['status', 'latitude', 'longitude'], name='idx_food_status_coords'),
        ),
        migrations.AddIndex(
            model_name='freefoodevent',
            index=models.Index(fields=['status', 'is_surplus_food', 'rescue_status'], name='idx_food_status_surplus'),
        ),
    ]
