# Generated by Django 6.1.1 on 2026-09-26 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximitySubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_km', models.FloatField(default=5.0, help_text='Proximity alert threshold in km (default: 5.0 km)')),
                ('push_enabled', models.BooleanField(default=True)),
                ('endpoint', models.CharField(blank=True, default='', help_text='Browser Web Push subscription endpoint or token', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximity_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'push_enabled'], name='notificatio_user_id_d0e4cb_idx'), models.Index(fields=['latitude', 'longitude'], name='notificatio_latitud_49714d_idx')],
            },
        ),
    ]
